function dot() {

  var data = {
    optgroup: ["world", "usa"],
    world: [
      'Africa',
      'Andorra',
      'Angola',
      'Argentina',
      'Armenia',
      'Australia',
      'Austria',
      'Azerbaijan',
      'Bahamas',
      'Bahrain',
      'Bangladesh',
      'Belarus',
      'Belgium',
      'Bhutan',
      'Bolivia',
      'Bosnia',
      'Botswana',
      'Brazil',
      'Brunei Darussalam',
      'Bulgaria',
      'Burkina Faso',
      'Burundi',
      'Cambodia',
      'Cameroon',
      'Canada',
      'Cape Verde',
      'Central African Republic',
      'Chad',
      'Chile',
      'China',
      'Colombia',
      'Congo',
      'Congo DR',
      'Costa Rica',
      'Croatia',
      'Cuba',
      'Cyprus',
      'Czech Republic',
      'Denmark',
      'Djibouti',
      'Dominican Republic',
      'Ecuador',
      'Egypt',
      'El Salvador',
      'Estonia',
      'Ethiopia',
      'Faroe Islands',
      'Finland',
      'France',
      'France Departments',
      'France New',
      'Georgia',
      'Germany',
      'Greece',
      'Guatemala',
      'Guinea',
      'Haiti',
      'Honduras',
      'Hong Kong',
      'Hungary',
      'Iceland',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Ireland',
      'Israel',
      'Italy',
      'Ivory Coast',
      'Jamaica',
      'Japan',
      'Kazakhstan',
      'Kenya',
      'Kosovo',
      'Kyrgyzstan',
      'Laos',
      'Latvia',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Macedonia',
      'Malaysia',
      'Mali',
      'Malta',
      'Mexico',
      'Moldova',
      'Montenegro',
      'Morocco',
      'Mozambique',
      'Myanmar',
      'Namibia',
      'Nepal',
      'Netherlands',
      'New Zealand',
      'Nicaragua',
      'Nigeria',
      'Norway',
      'Oman',
      'Pakistan',
      'Palestine',
      'Panama',
      'Paraguay',
      'Peru',
      'Philippines',
      'Poland',
      'Portugal',
      'Portugal Regions',
      'Puerto Rico',
      'Qatar',
      'Romania',
      'Russia',
      'Rwanda',
      'San Marino',
      'Saudi Arabia',
      'Serbia',
      'Sierra Leone',
      'Singapore',
      'Slovakia',
      'Slovenia',
      'South Africa',
      'South Korea',
      'Spain',
      'Spain provinces',
      'Sri Lanka',
      'Sudan',
      'Sweden',
      'Switzerland',
      'Syria',
      'Taiwan',
      'Tajikistan',
      'Thailand',
      'Turkey',
      'Uganda',
      'Ukraine',
      'United Arab Emirates',
      'United Kingdom',
      'Uruguay',
      'Uzbekistan',
      'Venezuela',
      'Vietnam',
      'Yemen',
      'Zambia',
      'Zimbabwe'
    ],
    usa: [
      'Alaska',
      'Alabama',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Denver',
      'Florida',
      'Georgia',
      'Hawaii',
      'Iowa',
      'Idaho',
      'Illinois',
      'Indiana',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Missouri',
      'Minnesota',
      'Mississippi',
      'Montana',
      'North Carolina',
      'North Dakota',
      'Nebraska',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'Nevada',
      'New York',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Virginia',
      'Vermont',
      'Washington',
      'Washington D.C.',
      'Wisconsin',
      'West Virginia',
      'Wyoming'
    ]
  }
  let s = document.createElement("select")

  for (let a = 0; a < 2; a++) {

    let u = document.createElement("optgroup")

    let t = data["optgroup"][a]
    u.label = t
    s.appendChild(u)
    for (let i in data[t]) {
      let o = document.createElement("option")

      o.innerText = data[t][i]
      o.value = data[t][i].replace(/" "/g, "-")
      s.appendChild(o)

    }

    $("#apl").html(s)
    return s
  }

}

var s = dot()


var data = {
  world: [
    'Africa',
    'Andorra',
    'Angola',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Belarus',
    'Belgium',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Congo',
    'Congo DR',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Estonia',
    'Ethiopia',
    'Faroe Islands',
    'Finland',
    'France',
    'France Departments',
    'France New',
    'Georgia',
    'Germany',
    'Greece',
    'Guatemala',
    'Guinea',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Kazakhstan',
    'Kenya',
    'Kosovo',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Malaysia',
    'Mali',
    'Malta',
    'Mexico',
    'Moldova',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Palestine',
    'Panama',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Portugal Regions',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'San Marino',
    'Saudi Arabia',
    'Serbia',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'South Korea',
    'Spain',
    'Spain provinces',
    'Sri Lanka',
    'Sudan',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'Uruguay',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
  ],
  usa: [
    'Alaska',
    'Alabama',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Denver',
    'Florida',
    'Georgia',
    'Hawaii',
    'Iowa',
    'Idaho',
    'Illinois',
    'Indiana',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Missouri',
    'Minnesota',
    'Mississippi',
    'Montana',
    'North Carolina',
    'North Dakota',
    'Nebraska',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'Nevada',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Virginia',
    'Vermont',
    'Washington',
    'Washington D.C.',
    'Wisconsin',
    'West Virginia',
    'Wyoming'
  ]
}

Array.prototype.allButlast = function(){
return this.slice(-1,0)
}

s.addEventListener("change", function (e) {

  if (data.world.indexOf(this.value) != -1) {
us(`imgs/${this.value.toLowerCase() }.svg`)
  }
  if (data.usa.indexOf(this.value) != -1) {
us(`imgs/usa/${this.value.toLowerCase() }.svg`)

  }
})

function us(url) {
  url = url.replace(/[' ']/g,"-")
  console.log( url )
   //
 // var url = url // "imgs/africa.svg"
  $.ajax({
    url: url,
    success: function (data) {
      if (url.split(".")[1] == "svg") {
        data = (new XMLSerializer()).serializeToString(data)
      }
      $("#map").html(data)
    },
    error: function (e) {
      console.log(e);
    }
  });
}


document.body.onclick = function (e) {
  if ($(e.target)[0].id == "") {

  } else {
    console.log($(e.target)[0].id)
  }
}





